/* eslint-disable max-lines */
import { describe, expect, it } from '@jest/globals';
import type { TMainMap } from './initializeC';
import { initializeC } from './initializeC';

const _notSearchInMsdn = [
    'gdiplus\\GdipGetLastStatus',
    'gdiplus\\GdipResetMatrix',

    'Kernel32.dll\\RtlMoveMemory',
    'RtlMoveMemory',
    'NTDLL\\RtlComputeCrc32',
    'Gdi32.dll\\DeleteDCA',

    'msvcrt\\', // TODO
    'Shcore.dll\\GetDpiForMonitor', // not in https://github.com/microsoft/windows-rs

    'RtlFillMemory',
];

const gdip = [
    'Gdiplus.dll\\GdipAddPathArc',
    'Gdiplus.dll\\GdipClosePathFigure',
    'Gdiplus.dll\\GdipCreatePath',
    'Gdiplus.dll\\GdipDeletePath',
    'Gdiplus.dll\\GdipDrawPath',
    'Gdiplus.dll\\GdipFillPath',
    'gdiplus\\GdipAddPathArc',
    'gdiplus\\GdipAddPathBezier',
    'gdiplus\\GdipAddPathBeziers',
    'gdiplus\\GdipAddPathClosedCurve',
    'gdiplus\\GdipAddPathClosedCurve2',
    'gdiplus\\GdipAddPathCurve',
    'gdiplus\\GdipAddPathCurve2',
    'gdiplus\\GdipAddPathEllipse',
    'gdiplus\\GdipAddPathLine',
    'gdiplus\\GdipAddPathLine2',
    'gdiplus\\GdipAddPathPie',
    'gdiplus\\GdipAddPathPolygon',
    'gdiplus\\GdipAddPathRectangle',
    'gdiplus\\GdipAddPathString',
    'gdiplus\\GdipBitmapApplyEffect',
    'gdiplus\\GdipBitmapConvertFormat',
    'gdiplus\\GdipBitmapGetHistogram',
    'gdiplus\\GdipBitmapGetHistogramSize',
    'gdiplus\\GdipBitmapGetPixel',
    'gdiplus\\GdipBitmapLockBits',
    'gdiplus\\GdipBitmapSetPixel',
    'gdiplus\\GdipBitmapSetResolution',
    'gdiplus\\GdipBitmapUnlockBits',
    'gdiplus\\GdipCloneBitmapArea',
    'gdiplus\\GdipCloneBrush',
    'gdiplus\\GdipCloneFont',
    'gdiplus\\GdipCloneFontFamily',
    'gdiplus\\GdipCloneImage',
    'gdiplus\\GdipCloneImageAttributes',
    'gdiplus\\GdipCloneMatrix',
    'gdiplus\\GdipClonePath',
    'gdiplus\\GdipClonePen',
    'gdiplus\\GdipCloneRegion',
    'gdiplus\\GdipCloneStringFormat',
    'gdiplus\\GdipClosePathFigure',
    'gdiplus\\GdipClosePathFigures',
    'gdiplus\\GdipCombineRegionPath',
    'gdiplus\\GdipCombineRegionRect',
    'gdiplus\\GdipCombineRegionRegion',
    'gdiplus\\GdipCreateBitmapFromFile',
    'gdiplus\\GdipCreateBitmapFromGdiDib',
    'gdiplus\\GdipCreateBitmapFromGraphics',
    'gdiplus\\GdipCreateBitmapFromHBITMAP',
    'gdiplus\\GdipCreateBitmapFromHICON',
    'gdiplus\\GdipCreateBitmapFromScan0',
    'gdiplus\\GdipCreateBitmapFromStream',
    'gdiplus\\GdipCreateCachedBitmap',
    'gdiplus\\GdipCreateEffect',
    'gdiplus\\GdipCreateFont',
    'gdiplus\\GdipCreateFontFamilyFromName',
    'gdiplus\\GdipCreateFontFromDC',
    'Gdiplus\\GdipCreateFontFromLogfontW',
    'gdiplus\\GdipCreateFromHDC',
    'Gdiplus\\GdipCreateFromHDC2',
    'gdiplus\\GdipCreateFromHWND',
    'gdiplus\\GdipCreateHatchBrush',
    'gdiplus\\GdipCreateHBITMAPFromBitmap',
    'gdiplus\\GdipCreateHICONFromBitmap',
    'gdiplus\\GdipCreateImageAttributes',
    'gdiplus\\GdipCreateLineBrush',
    'gdiplus\\GdipCreateLineBrushFromRect',
    'gdiplus\\GdipCreateMatrix',
    'gdiplus\\GdipCreateMatrix2',
    'gdiplus\\GdipCreatePath',
    'gdiplus\\GdipCreatePathGradient',
    'gdiplus\\GdipCreatePathGradientFromPath',
    'gdiplus\\GdipCreatePen1',
    'gdiplus\\GdipCreatePen2',
    'gdiplus\\GdipCreateRegion',
    'gdiplus\\GdipCreateRegionPath',
    'gdiplus\\GdipCreateRegionRect',
    'gdiplus\\GdipCreateSolidFill',
    'gdiplus\\GdipCreateStringFormat',
    'gdiplus\\GdipCreateTexture',
    'gdiplus\\GdipCreateTexture2',
    'gdiplus\\GdipCreateTextureIA',
    'gdiplus\\GdipDeleteBrush',
    'gdiplus\\GdipDeleteCachedBitmap',
    'gdiplus\\GdipDeleteEffect',
    'gdiplus\\GdipDeleteFont',
    'gdiplus\\GdipDeleteFontFamily',
    'gdiplus\\GdipDeleteGraphics',
    'gdiplus\\GdipDeleteMatrix',
    'gdiplus\\GdipDeletePath',
    'gdiplus\\GdipDeletePen',
    'gdiplus\\GdipDeletePrivateFontCollection',
    'gdiplus\\GdipDeleteRegion',
    'gdiplus\\GdipDeleteStringFormat',
    'gdiplus\\GdipDisposeImage',
    'gdiplus\\GdipDisposeImageAttributes',
    'gdiplus\\GdipDrawArc',
    'gdiplus\\GdipDrawBezier',
    'gdiplus\\GdipDrawBeziers',
    'gdiplus\\GdipDrawCachedBitmap',
    'gdiplus\\GdipDrawClosedCurve',
    'gdiplus\\GdipDrawClosedCurve2',
    'gdiplus\\GdipDrawCurve',
    'gdiplus\\GdipDrawCurve2',
    'gdiplus\\GdipDrawDriverString',
    'gdiplus\\GdipDrawEllipse',
    'gdiplus\\GdipDrawImage',
    'gdiplus\\GdipDrawImageFX',
    'gdiplus\\GdipDrawImagePointsRect',
    'gdiplus\\GdipDrawImageRect',
    'gdiplus\\GdipDrawImageRectRect',
    'gdiplus\\GdipDrawLine',
    'gdiplus\\GdipDrawLines',
    'gdiplus\\GdipDrawPath',
    'gdiplus\\GdipDrawPie',
    'gdiplus\\GdipDrawPolygon',
    'gdiplus\\GdipDrawRectangle',
    'gdiplus\\GdipDrawString',
    'gdiplus\\GdipFillClosedCurve',
    'gdiplus\\GdipFillClosedCurve2',
    'gdiplus\\GdipFillEllipse',
    'gdiplus\\GdipFillPath',
    'gdiplus\\GdipFillPie',
    'gdiplus\\GdipFillPolygon',
    'gdiplus\\GdipFillRectangle',
    'gdiplus\\GdipFillRegion',
    'gdiplus\\GdipFlattenPath',
    'gdiplus\\GdipFlush',
    'gdiplus\\GdipGetAllPropertyItems',
    'gdiplus\\GdipGetBrushType',
    'gdiplus\\GdipGetCellAscent',
    'gdiplus\\GdipGetCellDescent',
    'gdiplus\\GdipGetClip',
    'gdiplus\\GdipGetClipBounds',
    'gdiplus\\GdipGetCompositingMode',
    'gdiplus\\GdipGetCompositingQuality',
    'gdiplus\\GdipGetDC',
    'gdiplus\\GdipGetDpiX',
    'gdiplus\\GdipGetDpiY',
    'gdiplus\\GdipGetEffectParameterSize',
    'gdiplus\\GdipGetEmHeight',
    'gdiplus\\GdipGetEncoderParameterList',
    'gdiplus\\GdipGetEncoderParameterListSize',
    'gdiplus\\GdipGetFamily',
    'gdiplus\\GdipGetFamilyName',
    'gdiplus\\GdipGetFontCollectionFamilyList',
    'gdiplus\\GdipGetFontHeight',
    'gdiplus\\GdipGetFontHeightGivenDPI',
    'gdiplus\\GdipGetFontSize',
    'gdiplus\\GdipGetFontStyle',
    'gdiplus\\GdipGetFontUnit',
    'gdiplus\\GdipGetGenericFontFamilyMonospace',
    'gdiplus\\GdipGetGenericFontFamilySansSerif',
    'gdiplus\\GdipGetGenericFontFamilySerif',
    'gdiplus\\GdipGetHatchBackgroundColor',
    'gdiplus\\GdipGetHatchForegroundColor',
    'gdiplus\\GdipGetHatchStyle',
    'gdiplus\\GdipGetImageBounds',
    'gdiplus\\GdipGetImageDimension',
    'gdiplus\\GdipGetImageEncoders',
    'gdiplus\\GdipGetImageEncodersSize',
    'gdiplus\\GdipGetImageFlags',
    'gdiplus\\GdipGetImageGraphicsContext',
    'gdiplus\\GdipGetImageHeight',
    'gdiplus\\GdipGetImageHorizontalResolution',
    'gdiplus\\GdipGetImagePixelFormat',
    'gdiplus\\GdipGetImageRawFormat',
    'gdiplus\\GdipGetImageThumbnail',
    'gdiplus\\GdipGetImageType',
    'gdiplus\\GdipGetImageVerticalResolution',
    'gdiplus\\GdipGetImageWidth',
    'gdiplus\\GdipGetInterpolationMode',
    'gdiplus\\GdipGetLineBlendCount',
    'gdiplus\\GdipGetLineColors',
    'gdiplus\\GdipGetLineGammaCorrection',
    'gdiplus\\GdipGetLineRect',
    'gdiplus\\GdipGetLineSpacing',
    'gdiplus\\GdipGetLineTransform',
    'gdiplus\\GdipGetLineWrapMode',
    'gdiplus\\GdipGetPageScale',
    'gdiplus\\GdipGetPageUnit',
    'gdiplus\\GdipGetPathFillMode',
    'gdiplus\\GdipGetPathGradientCenterColor',
    'gdiplus\\GdipGetPathGradientCenterPoint',
    'gdiplus\\GdipGetPathGradientFocusScales',
    'gdiplus\\GdipGetPathGradientGammaCorrection',
    'gdiplus\\GdipGetPathGradientPointCount',
    'gdiplus\\GdipGetPathGradientRect',
    'gdiplus\\GdipGetPathGradientSurroundColorCount',
    'gdiplus\\GdipGetPathGradientSurroundColorsWithCount',
    'gdiplus\\GdipGetPathGradientTransform',
    'gdiplus\\GdipGetPathGradientWrapMode',
    'gdiplus\\GdipGetPathLastPoint',
    'gdiplus\\GdipGetPathPoints',
    'gdiplus\\GdipGetPathWorldBounds',
    'gdiplus\\GdipGetPenBrushFill',
    'gdiplus\\GdipGetPenColor',
    'gdiplus\\GdipGetPenCompoundArray',
    'gdiplus\\GdipGetPenCompoundCount',
    'gdiplus\\GdipGetPenDashArray',
    'gdiplus\\GdipGetPenDashCap197819',
    'gdiplus\\GdipGetPenDashCount',
    'gdiplus\\GdipGetPenDashOffset',
    'gdiplus\\GdipGetPenDashStyle',
    'gdiplus\\GdipGetPenEndCap',
    'gdiplus\\GdipGetPenFillType',
    'gdiplus\\GdipGetPenLineJoin',
    'gdiplus\\GdipGetPenMiterLimit',
    'gdiplus\\GdipGetPenMode',
    'gdiplus\\GdipGetPenStartCap',
    'gdiplus\\GdipGetPenTransform',
    'gdiplus\\GdipGetPenUnit',
    'gdiplus\\GdipGetPenWidth',
    'gdiplus\\GdipGetPixelOffsetMode',
    'gdiplus\\GdipGetPointCount',
    'gdiplus\\GdipGetPropertyCount',
    'gdiplus\\GdipGetPropertyIdList',
    'gdiplus\\GdipGetPropertyItem',
    'gdiplus\\GdipGetPropertyItemSize',
    'gdiplus\\GdipGetPropertySize',
    'gdiplus\\GdipGetRegionBounds',
    'gdiplus\\GdipGetRenderingOrigin',
    'gdiplus\\GdipGetSmoothingMode',
    'gdiplus\\GdipGetSolidFillColor',
    'gdiplus\\GdipGetStringFormatAlign',
    'gdiplus\\GdipGetStringFormatDigitSubstitution',
    'gdiplus\\GdipGetStringFormatFlags',
    'gdiplus\\GdipGetStringFormatHotkeyPrefix',
    'gdiplus\\GdipGetStringFormatLineAlign',
    'gdiplus\\GdipGetStringFormatTrimming',
    'gdiplus\\GdipGetTextContrast',
    'gdiplus\\GdipGetTextRenderingHint',
    'gdiplus\\GdipGetTextureImage',
    'gdiplus\\GdipGetTextureTransform',
    'gdiplus\\GdipGetTextureWrapMode',
    'gdiplus\\GdipGetVisibleClipBounds',
    'gdiplus\\GdipGetWorldTransform',
    'gdiplus\\GdipGraphicsClear',
    'gdiplus\\GdipImageGetFrameCount',
    'gdiplus\\GdipImageGetFrameDimensionsCount',
    'gdiplus\\GdipImageGetFrameDimensionsList',
    'gdiplus\\GdipImageRotateFlip',
    'gdiplus\\GdipImageSelectActiveFrame',
    'gdiplus\\GdipInitializePalette',
    'gdiplus\\GdipInvertMatrix',
    'gdiplus\\GdipIsClipEmpty',
    'gdiplus\\GdipIsEmptyRegion',
    'gdiplus\\GdipIsEqualRegion',
    'gdiplus\\GdipIsInfiniteRegion',
    'gdiplus\\GdipIsMatrixEqual',
    'gdiplus\\GdipIsMatrixIdentity',
    'gdiplus\\GdipIsMatrixInvertible',
    'gdiplus\\GdipIsOutlineVisiblePathPoint',
    'gdiplus\\GdipIsStyleAvailable',
    'gdiplus\\GdipIsVisibleClipEmpty',
    'gdiplus\\GdipIsVisiblePathPoint',
    'gdiplus\\GdipIsVisiblePoint',
    'gdiplus\\GdipIsVisibleRect',
    'gdiplus\\GdipIsVisibleRegionPoint',
    'gdiplus\\GdipIsVisibleRegionRect',
    'gdiplus\\GdipLoadImageFromFile',
    'gdiplus\\GdiplusShutdown',
    'gdiplus\\GdiplusStartup',
    'gdiplus\\GdipMeasureString',
    'gdiplus\\GdipMultiplyLineTransform',
    'gdiplus\\GdipMultiplyMatrix',
    'gdiplus\\GdipMultiplyPathGradientTransform',
    'gdiplus\\GdipMultiplyPenTransform',
    'gdiplus\\GdipMultiplyTextureTransform',
    'gdiplus\\GdipMultiplyWorldTransform',
    'gdiplus\\GdipNewPrivateFontCollection',
    'gdiplus\\GdipPrivateAddFontFile',
    'gdiplus\\GdipReleaseDC',
    'gdiplus\\GdipResetClip',
    'gdiplus\\GdipResetImageAttributes',
    'gdiplus\\GdipResetLineTransform',
    'gdiplus\\GdipResetPageTransform',
    'gdiplus\\GdipResetPath',
    'gdiplus\\GdipResetPathGradientTransform',
    'gdiplus\\GdipResetPenTransform',
    'gdiplus\\GdipResetTextureTransform',
    'gdiplus\\GdipResetWorldTransform',
    'Gdiplus\\GdipRestoreGraphics',
    'gdiplus\\GdipReversePath',
    'gdiplus\\GdipRotateLineTransform',
    'gdiplus\\GdipRotateMatrix',
    'gdiplus\\GdipRotatePathGradientTransform',
    'gdiplus\\GdipRotatePenTransform',
    'gdiplus\\GdipRotateTextureTransform',
    'gdiplus\\GdipRotateWorldTransform',
    'Gdiplus\\GdipSaveGraphics',
    'gdiplus\\GdipSaveImageToFile',
    'gdiplus\\GdipSaveImageToStream',
    'gdiplus\\GdipScaleLineTransform',
    'gdiplus\\GdipScaleMatrix',
    'gdiplus\\GdipScalePathGradientTransform',
    'gdiplus\\GdipScalePenTransform',
    'gdiplus\\GdipScaleTextureTransform',
    'gdiplus\\GdipScaleWorldTransform',
    'gdiplus\\GdipSetClipGraphics',
    'gdiplus\\GdipSetClipPath',
    'gdiplus\\GdipSetClipRect',
    'gdiplus\\GdipSetClipRegion',
    'gdiplus\\GdipSetCompositingMode',
    'gdiplus\\GdipSetCompositingQuality',
    'gdiplus\\GdipSetEffectParameters',
    'gdiplus\\GdipSetEmpty',
    'gdiplus\\GdipSetImageAttributesColorKeys',
    'gdiplus\\GdipSetImageAttributesColorMatrix',
    'gdiplus\\GdipSetImageAttributesGamma',
    'gdiplus\\GdipSetImageAttributesNoOp',
    'gdiplus\\GdipSetImageAttributesOutputChannel',
    'gdiplus\\GdipSetImageAttributesThreshold',
    'gdiplus\\GdipSetImageAttributesToIdentity',
    'gdiplus\\GdipSetImageAttributesWrapMode',
    'gdiplus\\GdipSetInfinite',
    'gdiplus\\GdipSetInterpolationMode',
    'gdiplus\\GdipSetLineColors',
    'gdiplus\\GdipSetLineGammaCorrection',
    'gdiplus\\GdipSetLineLinearBlend',
    'gdiplus\\GdipSetLinePresetBlend',
    'gdiplus\\GdipSetLineSigmaBlend',
    'gdiplus\\GdipSetLineTransform',
    'gdiplus\\GdipSetLineWrapMode',
    'gdiplus\\GdipSetMatrixElements',
    'gdiplus\\GdipSetPageScale',
    'gdiplus\\GdipSetPageUnit',
    'gdiplus\\GdipSetPathFillMode',
    'gdiplus\\GdipSetPathGradientCenterColor',
    'gdiplus\\GdipSetPathGradientCenterPoint',
    'gdiplus\\GdipSetPathGradientFocusScales',
    'gdiplus\\GdipSetPathGradientGammaCorrection',
    'gdiplus\\GdipSetPathGradientLinearBlend',
    'gdiplus\\GdipSetPathGradientSigmaBlend',
    'gdiplus\\GdipSetPathGradientSurroundColorsWithCount',
    'gdiplus\\GdipSetPathGradientTransform',
    'gdiplus\\GdipSetPathGradientWrapMode',
    'gdiplus\\GdipSetPenBrushFill',
    'gdiplus\\GdipSetPenColor',
    'gdiplus\\GdipSetPenCompoundArray',
    'gdiplus\\GdipSetPenDashArray',
    'gdiplus\\GdipSetPenDashCap197819',
    'gdiplus\\GdipSetPenDashOffset',
    'gdiplus\\GdipSetPenDashStyle',
    'gdiplus\\GdipSetPenEndCap',
    'gdiplus\\GdipSetPenLineCap197819',
    'gdiplus\\GdipSetPenLineJoin',
    'gdiplus\\GdipSetPenMiterLimit',
    'gdiplus\\GdipSetPenMode',
    'gdiplus\\GdipSetPenStartCap',
    'gdiplus\\GdipSetPenTransform',
    'gdiplus\\GdipSetPenUnit',
    'gdiplus\\GdipSetPenWidth',
    'gdiplus\\GdipSetPixelOffsetMode',
    'gdiplus\\GdipSetRenderingOrigin',
    'gdiplus\\GdipSetSmoothingMode',
    'gdiplus\\GdipSetSolidFillColor',
    'gdiplus\\GdipSetStringFormatAlign',
    'gdiplus\\GdipSetStringFormatDigitSubstitution',
    'gdiplus\\GdipSetStringFormatFlags',
    'gdiplus\\GdipSetStringFormatHotkeyPrefix',
    'gdiplus\\GdipSetStringFormatLineAlign',
    'gdiplus\\GdipSetStringFormatTrimming',
    'gdiplus\\GdipSetTextContrast',
    'gdiplus\\GdipSetTextRenderingHint',
    'gdiplus\\GdipSetTextureTransform',
    'gdiplus\\GdipSetTextureWrapMode',
    'gdiplus\\GdipSetWorldTransform',
    'gdiplus\\GdipStartPathFigure',
    'gdiplus\\GdipStringFormatGetGenericDefault',
    'gdiplus\\GdipStringFormatGetGenericTypographic',
    'gdiplus\\GdipTransformPath',
    'gdiplus\\GdipTransformRegion',
    'gdiplus\\GdipTranslateClip',
    'gdiplus\\GdipTranslateLineTransform',
    'gdiplus\\GdipTranslateMatrix',
    'gdiplus\\GdipTranslatePathGradientTransform',
    'gdiplus\\GdipTranslatePenTransform',
    'gdiplus\\GdipTranslateRegion',
    'gdiplus\\GdipTranslateTextureTransform',
    'gdiplus\\GdipTranslateWorldTransform',
    'gdiplus\\GdipWidenPath',
    'gdiplus\\GdipWindingModeOutline',
];

const t1 = [
    ...gdip,
    'ClientToScreen',
    'CloseClipboard',
    'Comctl32.dll\\DefSubclassProc',
    'Comctl32.dll\\RemoveWindowSubclass',
    'Comctl32.dll\\SetWindowSubclass',
    'CreateCompatibleDC',
    'CreateDIBSection',
    'CreatePopupMenu',
    'Crypt32.dll\\CryptBinaryToStringA',
    'crypt32\\CryptStringToBinaryA',
    'DeleteDC',
    'DeleteObject',
    'DestroyIcon',
    'DestroyMenu',
    'DrawIconEx',
    'dwmapi\\DwmGetWindowAttribute',
    'EmptyClipboard',
    'ExpandEnvironmentStringsA',
    'FreeLibrary',
    'Gdi32.dll\\CreateDCA',
    'Gdi32.dll\\GetDeviceCaps',
    'gdi32\\BitBlt',
    'gdi32\\GetObjectA',
    'gdi32\\SetStretchBltMode',
    'gdi32\\StretchBlt',
    'GetClientRect',
    'GetClipboardData',
    'GetCurrentProcessId',
    'GetCursorPos',
    'GetDC',
    'GetDCEx',
    'GetIconInfo',
    'GetModuleHandleW',
    'GetObjectA',
    'GetSysColor',
    'GetSystemMetrics',
    'GetVersion',
    'GetWindowRect',
    'GlobalAlloc',
    'GlobalFree',
    'GlobalLock',
    'GlobalSize',
    'GlobalUnlock',
    'ImageList_ReplaceIcon',
    'InsertMenuW',
    'IsClipboardFormatAvailable',
    'IsIconic',
    'Kernel32.dll\\GetVersion',
    'LoadCursorW',
    'LoadLibraryW',
    'lstrcpynW',
    'lstrlenW',
    'MultiByteToWideChar',
    'Ole32.dll\\CreateStreamOnHGlobal',
    'ole32.dll\\StringFromGUID2',
    'ole32\\CLSIDFromString',
    'ole32\\CoInitialize',
    'ole32\\CoTaskMemFree',
    'ole32\\CoUninitialize',
    'ole32\\CreateStreamOnHGlobal',
    'ole32\\GetHGlobalFromStream',
    'ole32\\StringFromGUID2',
    'OpenClipboard',
    'PaintDesktop',
    'PrintWindow',
    'PrivateExtractIconsW',
    'RegisterClipboardFormatW',
    'ReleaseDC',
    'SelectObject',
    'SendMessageA',
    'SetClipboardData',
    'SetWindowLongPtrA',
    'SetWindowPos',
    'Shell32\\ExtractAssociatedIconA',
    'shell32\\SHBindToObject',
    'shell32\\SHGetFolderLocation',
    'shell32\\SHOpenFolderAndSelectItems',
    'shell32\\SHParseDisplayName',
    'shlwapi\\PathCreateFromUrlA',
    'shlwapi\\SHCreateMemStream',
    'ShowWindow',
    'SystemParametersInfoA',
    'TrackPopupMenuEx',
    'UpdateLayeredWindow',
    'user32.dll\\CallWindowProcW',
    'User32.dll\\CopyImage',
    'User32.dll\\EnumDisplayMonitors',
    'User32.dll\\GetClipboardData',
    'User32.dll\\GetCursorPos',
    'User32.dll\\GetMonitorInfoA',
    'User32.dll\\IsWindow',
    'User32.dll\\MonitorFromPoint',
    'User32.dll\\MonitorFromRect',
    'User32.dll\\MonitorFromWindow',
    'user32\\GetIconInfo',
    'VirtualProtect',
    'WideCharToMultiByte',
    'wsprintfW',
];

describe('check nls', () => {
    it('check : nls', () => {
        expect.hasAssertions();

        const errList0: string[] = [];
        // const log: string[] = [];
        const mainMap: TMainMap = initializeC();

        for (const s of t1) {
            const i = s.indexOf('\\');
            if (i > 0) {
                const dllName1: string = s.slice(0, i);
                const dllName1Up: string = dllName1.toUpperCase();
                const dllName2Up: string = dllName1Up.endsWith('.DLL')
                    ? dllName1Up
                    : `${dllName1Up}.DLL`;
                //
                const fnName: string = s.slice(i + 1);
                const fnNameUp: string = fnName.toUpperCase();

                const dllDef = mainMap.get(dllName2Up);
                if (dllDef === undefined) {
                    errList0.push(`${dllName1} not find`);
                    continue;
                }
                const fnDef = dllDef.dllMap.get(fnNameUp);
                if (fnDef === undefined) {
                    errList0.push(`${dllName1}/${fnName} not find`);
                    continue;
                }
            } else {
                //
                const fnName: string = s;
                const fnNameUp: string = fnName.toUpperCase();

                let isFind = false;
                for (const dllName of ['User32.dll', 'Kernel32.dll', 'ComCtl32.dll', 'Gdi32.dll']) {
                    const dllName2Up: string = dllName.toUpperCase();
                    const dllDef = mainMap.get(dllName2Up);
                    if (dllDef === undefined) {
                        errList0.push(`${dllName} not find`);
                        continue;
                    }

                    const fnDef = dllDef.dllMap.get(fnNameUp);
                    if (fnDef !== undefined) {
                        isFind = true;
                        break;
                    }
                }
                if (!isFind) {
                    errList0.push(`${fnName} not find`);
                }
            }
        }

        expect(errList0).toHaveLength(0);
    });
});
